### ISSUE TITLE
Reflection Warning on REPL Start

### ISSUE THREAD

**Issue by OriginalFenno** [cognitect/transit-clj#40]
Hi,
I've started getting a Reflection warning:
"Reflection warning, cognitect/transit.clj:142:19 - call to static method writer on com.cognitect.transit.TransitFactory can't be resolved (argument types: unknown, java.io.OutputStream, unknown)."
Reproduced in Java SE 8u152, using Clojure 1.8.0 and Clojure 1.9.0; the error only appears when I uncomment the following function definition:
``` clojure
(defn connect-testdb
  []
  (def conn
   (<!!
     (client/connect
       {:db-name "test"
        :account-id client/PRO_ACCOUNT
        :access-key *****
        :secret *****
        :region "none"
        :endpoint "localhost:8998"
        :service "peer-server"}))))
```

**Comment by puredanger** [comment]
Your example seems to be based in your app, pretty far from where Transit is used. Can you provide the version of transit-clj and transit-java you're using and a simple test that just uses Transit? It would also be useful to know what you are invoking cognitect.transit/writer with.

I ran this on the latest:

```clojure
(require '[cognitect.transit :as t])
(set! *warn-on-reflection* true)

;; example where types will be known
(t/writer System/out :json)  ;; no warning

;; example where parameter types are obscured, more similar to the report 
(defn make-writer [stream type]
  (t/writer stream type))
(make-writer System/out :json) ;; no warning
```

and did not see a warning in either case.

**Comment by OriginalFenno** [comment]
Hi,
Apologies for the long delay! I received this error when using the Datomic client library - I'm in the early days of my Clojure career (with no Java background), and I now appreciate that the issue is unlikely to be within transit-clj itself. I'll see if there's anywhere on the Datomic website I can report the issue, and hopefully provide more useful information there. Please feel free to close this issue, and thanks for responding.
Tom

**Comment by eneroth** [comment]
Just to chime in, I'm getting the same after I added transit to the Datomic Ions tutorial project.

**Comment by puredanger** [comment]
Looks like this was caused by the addition of the new variant in transit-java / TransitFactory.writer() where there are two 3-arity forms, one with defaultWriteHandler and one with customHandlers (the desired one was the latter). However, the addition of the transform arity and change to use that new 5-arity form resolved this ambiguity as of release 0.8.307 of transit-clj. So, I think there is nothing further to be done here (Datomic client needs to bump it's version up to latest to use it.)

**Comment by puredanger** [comment]
In particular, using a new transit-java with an old transit-clj is sufficient to repro:

```$ clj -Sdeps '{:deps {com.cognitect/transit-clj {:mvn/version "0.8.285"} com.cognitect/transit-java {:mvn/version "0.8.337"}}}'
Clojure 1.9.0
user=> (set! *warn-on-reflection* true)
true
user=> (require '[cognitect.transit :as t])
Reflection warning, cognitect/transit.clj:143:19 - call to static method writer on com.cognitect.transit.TransitFactory can't be resolved (argument types: unknown, java.io.OutputStream, unknown).
nil```

but with newer transit-clj:

```$ clj -Sdeps '{:deps {com.cognitect/transit-clj {:mvn/version "0.8.309"} com.cognitect/transit-java {:mvn/version "0.8.337"}}}'
Clojure 1.9.0
user=> (set! *warn-on-reflection* true)
true
user=> (require '[cognitect.transit :as t])
nil```

**Comment by puredanger** [comment]
I'm working on getting the Datomic libs updated, but again, this has already been fixed here in transit-clj so nothing else to do - going to close.

**Comment by conan** [comment]
I still see this when using the latest versions of datomic client and transit-clj:
```
com.cognitect/transit-clj {:mvn/version "0.8.313"}
com.datomic/client-cloud {:mvn/version "0.8.71"}
```

**Comment by puredanger** [comment]
These warnings are different than the original issue and seem to point to calls in client-cloud, not transit-clj.
